# Generated by Django 4.2.10 on 2024-02-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updtated_on',
            new_name='updated_on',
        ),
    ]
